version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: boilerplate_catalog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./database/docker_compose_sql_script/init_table.sql:/docker-entrypoint-initdb.d/1001.sql
