
-- +migrate Up
CREATE TABLE products (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar NOT NULL,
    "category_id" int NOT NULL,
    "stock" int NOT NULL,
    "price" float NOT NULL
);

-- +migrate Down
DROP TABLE products;